name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: curl http://httpbin.org/ip
      - run: curl -v https://www.lowes.com/robots.txt
